import Head from 'next/head';
import { Fragment } from 'react';

export default function About() {

  return (
    <Fragment>

      <Head>
        <title> Head  test </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2> about </h2>

    </Fragment>

  )
}