import Head from 'next/head';
import { Fragment } from 'react';
// import { getRecentPosts } from '../utils/mdxUtil.js';
// import PostCard from '../components/PostCard.js';
// import RelatedPost from '../components/RelatedPost.js';

export default function Home({ posts }) {

  return (
    <Fragment>

      <Head>
        <title> Head  test </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2> all posts </h2>


      {/* <div className='posts'>

        <PostCard key={posts[0].slug} post={posts[0]} priority />


        {posts.slice(1, posts.length).map((post) => {
          return <RelatedPost key={post.slug} post={post}/>
        })}
        
      </div> */}

    </Fragment>

  )
}

// export async function getServerSideProps() {

//       const posts = [];

//       return {
//     props: {
//       posts //: await getRecentPosts()
//     }
//   }
// }

// export async function getStaticProps() {
  
//   return {
//     props: {
//       posts: await getRecentPosts()
//     }
//   }
// }