import Head from 'next/head';
import { Fragment } from 'react/cjs/react.production.min';
import { getRecentPosts } from '../utils/mdxUtil.js';
import PostCard from '../components/PostCard.js';
import RelatedPost from '../components/RelatedPost.js';

export default function Home({ posts }) {

  return (
    <Fragment>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='posts'>

        <PostCard key={posts[0].slug} post={posts[0]} priority />

        <h2> Recently added </h2>

        {posts.slice(1, posts.length).map((post) => {
          return <RelatedPost key={post.slug} post={post}/>
        })}

      </div>

    </Fragment>

  )
}

export async function getStaticProps() {

  return {
    props: {
      posts: await getRecentPosts()
    }
  }
} 