import Head from 'next/head';
import Image from 'next/image';
import { Fragment } from 'react/cjs/react.production.min';
import Page from '../components/Page.js';
import { postFilePaths, POSTS_PATH } from '../utils/mdxUtil.js';
import PostCard from '../components/PostCard.js';
import matter from 'gray-matter';
import { readFileSync } from 'fs';
import path from 'path';

export default function Home({ posts }) {
  return (
    <Fragment>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page>

      <div className='posts'>

        {posts.map((post) => {
          return <PostCard key={post.slug} post={post}/>
        })}
      </div>

      </Page>
    </Fragment>

  )
}

export async function getStaticProps() {

  const posts = postFilePaths.map((filePath) => {
    const source = readFileSync(path.join(POSTS_PATH, filePath))
    const { data } = matter(source);

    return data;
  })

  return {
    props: {
      posts
    }
  }
}