import Head from 'next/head';
import Image from 'next/image';
import { Fragment } from 'react/cjs/react.production.min';
import Page from '../components/Page.js';
import { getPosts } from '../lib/api';
import PostCard from '../components/PostCard.js';

export default function Home({ posts }) {
  return (
    <Fragment>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page>

      <div className='posts'>

        {posts.map((post) => {
          return <PostCard key={post.slug} post={post}/>
        })}
      </div>

      </Page>
    </Fragment>

  )
}

export async function getStaticProps() {

  const posts = await getPosts();

  return {
    props: {
      posts
    }
  }
}